[
    {
        "code2": "0001",
        "planeType": "Boeing 787",
        "totalSeats": 200,
        "toAirport": "LAX",
        "takeOffDate": "2016-01-20T05:30:00",
        "fromAirport": "MUA",
        "price": 541,
        "airlineName": "American Airlines",
        "seatsAvailable": 0,
        "ID": 1,
        "code1": "rree"
    },
    {
        "code2": "0123",
        "planeType": "Boeing 747",
        "totalSeats": 345,
        "toAirport": "CLE",
        "takeOffDate": "2016-01-25T05:30:00",
        "fromAirport": "MUA",
        "price": 300,
        "airlineName": "American Airlines",
        "seatsAvailable": 7,
        "ID": 2,
        "code1": "eefd"
    },
    {
        "code2": "0192",
        "planeType": "Boeing 777",
        "totalSeats": 300,
        "toAirport": "LAX",
        "takeOffDate": "2016-01-20T05:30:00",
        "fromAirport": "MUA",
        "price": 300,
        "airlineName": "American Airlines",
        "seatsAvailable": 0,
        "ID": 3,
        "code1": "ffee"
    },
    {
        "code2": "1000",
        "planeType": "Boeing 737",
        "totalSeats": 150,
        "toAirport": "CLE",
        "takeOffDate": "2016-01-20T05:30:00",
        "fromAirport": "MUA",
        "price": 200,
        "airlineName": "American Airlines",
        "seatsAvailable": 5,
        "ID": 4,
        "code1": "rree"
    },
    {
        "code2": "1093",
        "planeType": "Boeing 737",
        "totalSeats": 150,
        "toAirport": "SFO",
        "takeOffDate": "2016-02-11T05:30:00",
        "fromAirport": "MUA",
        "price": 142,
        "airlineName": "American Airlines",
        "seatsAvailable": 1,
        "ID": 5,
        "code1": "rree"
    },
    {
        "code2": "1112",
        "planeType": "Boeing 787",
        "totalSeats": 200,
        "toAirport": "CLE",
        "takeOffDate": "2016-01-20T05:30:00",
        "fromAirport": "MUA",
        "price": 954,
        "airlineName": "American Airlines",
        "seatsAvailable": 100,
        "ID": 6,
        "code1": "ffee"
    },
    {
        "code2": "1994",
        "planeType": "Boeing 777",
        "totalSeats": 300,
        "toAirport": "SFO",
        "takeOffDate": "2016-01-01T05:30:00",
        "fromAirport": "MUA",
        "price": 676,
        "airlineName": "American Airlines",
        "seatsAvailable": 0,
        "ID": 7,
        "code1": "eefd"
    },
    {
        "code2": "2000",
        "planeType": "Boeing 737",
        "totalSeats": 150,
        "toAirport": "SFO",
        "takeOffDate": "2016-02-20T05:30:00",
        "fromAirport": "MUA",
        "price": 300,
        "airlineName": "American Airlines",
        "seatsAvailable": 30,
        "ID": 8,
        "code1": "ffee"
    },
    {
        "code2": "3000",
        "planeType": "Boeing 737",
        "totalSeats": 150,
        "toAirport": "SFO",
        "takeOffDate": "2016-02-01T05:30:00",
        "fromAirport": "MUA",
        "price": 900,
        "airlineName": "American Airlines",
        "seatsAvailable": 0,
        "ID": 9,
        "code1": "eefd"
    },
    {
        "code2": "4511",
        "planeType": "Boeing 777",
        "totalSeats": 300,
        "toAirport": "LAX",
        "takeOffDate": "2016-01-15T05:30:00",
        "fromAirport": "MUA",
        "price": 900,
        "airlineName": "American Airlines",
        "seatsAvailable": 100,
        "ID": 10,
        "code1": "eefd"
    },
    {
        "code2": "4567",
        "planeType": "Boeing 737",
        "totalSeats": 150,
        "toAirport": "SFO",
        "takeOffDate": "2016-01-20T05:30:00",
        "fromAirport": "MUA",
        "price": 456,
        "airlineName": "American Airlines",
        "seatsAvailable": 100,
        "ID": 11,
        "code1": "rree"
    }
]